version: "3.9"
services:
  back:
    image: "back-img:latest"
    ports:
      - "5001:80"
    networks:
      - lancheria
  front:
    image: "front-img:latest"
    ports:
      - "3000:3000"
    networks:
    - lancheria
    
networks:
  lancheria:
    driver: bridge