version: 2.1
jobs:
  build:
    working_directory: ./projetolancheria-frontend
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies/
          path: ./projetolancheria-frontend/
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./projetolancheria-frontend/node_modules
      - run:
          name: run tests
          path: ./projetolancheria-frontend/
          command: npm test
      - store_artifacts:
          path: ~/repo/circlecitest